name: crop-recommendation-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - jupyter
  - pip
  - pip:
    - pytest
